'use strict';

var React = require('react-native');
var ViewCreatedTour = require('./ViewCreatedTour');
var utils = require('../lib/utility');
var t = require('tcomb-form-native');
var Form = t.form.Form;

var {
  Component,
  StyleSheet,
  Text,
  TextInput,
  TouchableHighlight,
  View,
} = React;

// Place defines domain model for form.
var Place = t.struct({
  placeName: t.maybe(t.String),
  address: t.maybe(t.String),
  description: t.maybe(t.String),
  placeOrder: t.maybe(t.Number)
});

var options = {};

class AddPlace extends Component {
  
  /**
   * Creates an instance of AddPlace.
   */
  constructor(props) {
    super(props);
    this.state = {
      tour: this.props.tour
    };
  }

  /**
   * Gets place details using tcomb-form-native getValue method and posts it in the database.
   */
  onPressSave () {
    /**
     * getValue() gets the values of the form.
     */
    var newPlace = this.refs.form.getValue();
    console.log('new place added: ', newPlace);
    var tour = this.state.tour;
    var tourId = this.state.tour.id;

    utils.makeRequest('addPlace', newPlace, tourId)
      .then(response => {
        console.log('response body in Add Place: '. response);
        var tour = response;
        utils.navigateTo.call(this, "View Tour", ViewCreatedTour, {tour});
      });
  }

  /**
   * renders a form generated by tcomb-form-native based on the domain model 'Place'.
   */
  render () {
    return (
      <View style={ styles.container }>
      {/* display */}
      <Form
        ref="form"
        type={ Place }
        options={ options }/>

      <TouchableHighlight style={ styles.button } onPress={ this.onPressSave.bind(this) } underlayColor='#99d9f4'>
        <Text style={ styles.buttonText }>Save</Text>
      </TouchableHighlight>
    </View>
    );
  }
}

var styles = StyleSheet.create({
  container: {
    justifyContent: 'center',
    marginTop: 50,
    padding: 20,
    backgroundColor: '#ffffff',
  },
  title: {
    fontSize: 30,
    alignSelf: 'center',
    marginBottom: 30
  },
  buttonText: {
    fontSize: 18,
    color: 'white',
    alignSelf: 'center'
  },
  button: {
    height: 36,
    backgroundColor: '#FF3366',
    borderColor: '#48BBEC',
    borderWidth: 1,
    borderRadius: 8,
    marginBottom: 10,
    alignSelf: 'stretch',
    justifyContent: 'center'
  }
});

module.exports = AddPlace;
